name: RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:

      - name: Enable RDP
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

          net user RDP Password123! /add
          net localgroup administrators RDP /add
          net localgroup "Remote Desktop Users" RDP /add

      - name: Download Tailscale
        shell: powershell
        run: |
          Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi -OutFile tailscale.msi

          Start-Process msiexec.exe -ArgumentList "/i tailscale.msi /quiet /norestart" -Wait

      - name: Connect Tailscale
        shell: powershell
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Show Details
        shell: powershell
        run: |
          $ip = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4

          Write-Host "====================="
          Write-Host "RDP READY"
          Write-Host "IP: $ip"
          Write-Host "USER: RDP"
          Write-Host "PASS: Password123!"
          Write-Host "====================="

      - name: Keep Alive
        shell: powershell
        run: |
          while ($true) {
            Start-Sleep -Seconds 300
          }
